### ISSUE TITLE
Unwanted dependency registered to the own type ("with" builder pattern)

### ISSUE THREAD

**Issue by gushakov** [Chetkov/php-clean-architecture#11]
Hi Valeriy,

Thank you very much for this excellent software and the accompanying articles on Habr. I've used it in my recent project, which may be of interest to you. 

https://github.com/gushakov/clean-php

There is one thing that I have noticed. I'm using a builder or "with" pattern with my domain models which allow me to create a copy of each domain object with only one property modified (and the others copied as is), something like this:

```php
class Greeting
{

    private readonly string $text;

    public function __construct(string $text)
    {
        $this->text = $text;
    }

    /**
     * Returns new Greeting with modified text.
     */
    public function withText(string $text): Greeting
    {
        return new Greeting($text);
    }

}
```

This setup gives me a strange dependency from "Greeting" back to "Greeting" (itself) when I run `phpca-build-reports` script. I think it maybe a bug.

С уважением и с наилучшими пожеланиями,

George

**Comment by Chetkov** [comment]
Hello, thanks for your feedback.

I cloned your "clean-php" project and built phpca-report.
It really was a bug:
![image](https://user-images.githubusercontent.com/12594577/221945022-401ac2f4-06c8-4de1-a829-f575b812cb95.png)

I fixed it in [this commit](https://github.com/Chetkov/php-clean-architecture/commit/a980ee9abe0e291ef3eea16b84529f43df7e22e0)

Now it looks like this:
![image](https://user-images.githubusercontent.com/12594577/221945296-6b587d45-a3c6-49f7-b548-a29a33bfc1a2.png)

You can use version 0.1.3, which already exists the bugfix.

Good evening!
